# Generated by Django 4.0.3 on 2022-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Image ID')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('mid', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Merchandise ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
            options={
                'db_table': 'Merchandise',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sid', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=20, verbose_name='Password')),
                ('introduction', models.TextField(default='', verbose_name='Personal introduction')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('portrait', models.ImageField(default='/media/portrait/default.jpg', upload_to='portrait', verbose_name='User portrait')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
