# Generated by Django 4.0.3 on 2022-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuSell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='keyword',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='contact',
            field=models.CharField(default='', max_length=15, verbose_name='Contact'),
        ),
    ]
