# Generated by Django 4.0.3 on 2022-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuSell', '0002_alter_merchandise_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=10, verbose_name='User ID')),
                ('mid', models.CharField(default='', max_length=10, verbose_name='Merchandise ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Add time')),
            ],
            options={
                'db_table': 'Liked',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
